clear; close all; clc;
f = imread('../raw_data/aaa.jpg');
f = rgb2gray(f);
%f = imnoise(f, 'salt & pepper');
f = imnoise(f, 'gaussian');
%f = imnoise(f, 'poisson');
subplot('Position', [0 .5 .5 .5]), imshow(f);
F = nonlinear_filter('med', f, [13 13]);
g = f-0.5*f+0.5*F;
F = nonlinear_filter('min', g, [5 5]);
subplot('Position', [0 0 .5 .5]), imshow(F);